# Generated by Django 4.1.3 on 2022-11-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='section',
            new_name='password',
        ),
    ]
