# Generated by Django 4.1.3 on 2022-11-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_posts_comment_owner_varet_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='api.post')),
            ],
        ),
    ]
